/// Summary statistics for the dashboard
class DashboardSummary {
  /// Total number of clients
  final int totalClients;

  /// Number of tax returns that have been filed
  final int filedReturns;

  /// Number of tax returns pending filing
  final int pendingReturns;

  /// Number of tasks that are overdue
  final int overdueTasks;

  /// Number of upcoming deadlines in the next 30 days
  final int upcomingDeadlines;

  /// Total billing amount (in appropriate currency units)
  final double totalBilling;

  /// Creates a [DashboardSummary] instance
  const DashboardSummary({
    required this.totalClients,
    required this.filedReturns,
    required this.pendingReturns,
    required this.overdueTasks,
    required this.upcomingDeadlines,
    required this.totalBilling,
  });

  /// Creates a copy of this [DashboardSummary] with updated fields
  DashboardSummary copyWith({
    int? totalClients,
    int? filedReturns,
    int? pendingReturns,
    int? overdueTasks,
    int? upcomingDeadlines,
    double? totalBilling,
  }) {
    return DashboardSummary(
      totalClients: totalClients ?? this.totalClients,
      filedReturns: filedReturns ?? this.filedReturns,
      pendingReturns: pendingReturns ?? this.pendingReturns,
      overdueTasks: overdueTasks ?? this.overdueTasks,
      upcomingDeadlines: upcomingDeadlines ?? this.upcomingDeadlines,
      totalBilling: totalBilling ?? this.totalBilling,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DashboardSummary &&
          runtimeType == other.runtimeType &&
          totalClients == other.totalClients &&
          filedReturns == other.filedReturns &&
          pendingReturns == other.pendingReturns &&
          overdueTasks == other.overdueTasks &&
          upcomingDeadlines == other.upcomingDeadlines &&
          totalBilling == other.totalBilling;

  @override
  int get hashCode =>
      totalClients.hashCode ^
      filedReturns.hashCode ^
      pendingReturns.hashCode ^
      overdueTasks.hashCode ^
      upcomingDeadlines.hashCode ^
      totalBilling.hashCode;

  @override
  String toString() =>
      'DashboardSummary(totalClients: $totalClients, filedReturns: $filedReturns, pendingReturns: $pendingReturns, overdueTasks: $overdueTasks, upcomingDeadlines: $upcomingDeadlines, totalBilling: $totalBilling)';
}

/// Represents a recently filed tax return
class RecentFiling {
  /// Name of the client who filed the return
  final String clientName;

  /// Type of filing (e.g., ITR, GST, TDS)
  final String filingType;

  /// Current status of the filing (e.g., Submitted, Accepted, Rejected)
  final String status;

  /// Date when the filing was submitted or processed
  final DateTime date;

  /// Creates a [RecentFiling] instance
  const RecentFiling({
    required this.clientName,
    required this.filingType,
    required this.status,
    required this.date,
  });

  /// Creates a copy of this [RecentFiling] with updated fields
  RecentFiling copyWith({
    String? clientName,
    String? filingType,
    String? status,
    DateTime? date,
  }) {
    return RecentFiling(
      clientName: clientName ?? this.clientName,
      filingType: filingType ?? this.filingType,
      status: status ?? this.status,
      date: date ?? this.date,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RecentFiling &&
          runtimeType == other.runtimeType &&
          clientName == other.clientName &&
          filingType == other.filingType &&
          status == other.status &&
          date == other.date;

  @override
  int get hashCode =>
      clientName.hashCode ^
      filingType.hashCode ^
      status.hashCode ^
      date.hashCode;

  @override
  String toString() =>
      'RecentFiling(clientName: $clientName, filingType: $filingType, status: $status, date: $date)';
}

/// Represents a top performing client by filing activity and billing
class TopClient {
  /// Name of the client
  final String clientName;

  /// Number of filings completed by this client
  final int filingCount;

  /// Total billing amount generated by this client (in appropriate currency units)
  final double billingAmount;

  /// Creates a [TopClient] instance
  const TopClient({
    required this.clientName,
    required this.filingCount,
    required this.billingAmount,
  });

  /// Creates a copy of this [TopClient] with updated fields
  TopClient copyWith({
    String? clientName,
    int? filingCount,
    double? billingAmount,
  }) {
    return TopClient(
      clientName: clientName ?? this.clientName,
      filingCount: filingCount ?? this.filingCount,
      billingAmount: billingAmount ?? this.billingAmount,
    );
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TopClient &&
          runtimeType == other.runtimeType &&
          clientName == other.clientName &&
          filingCount == other.filingCount &&
          billingAmount == other.billingAmount;

  @override
  int get hashCode =>
      clientName.hashCode ^ filingCount.hashCode ^ billingAmount.hashCode;

  @override
  String toString() =>
      'TopClient(clientName: $clientName, filingCount: $filingCount, billingAmount: $billingAmount)';
}
