import 'package:ca_app/features/tds/domain/models/tds_section_rate.dart';

/// Static TDS rate chart data for all financial years.
///
/// This file contains ONLY the rate data. Business logic lives in
/// [TdsRateEngine].
class TdsRateData {
  TdsRateData._();

  /// Complete TDS/TCS rate chart for FY 2025-26.
  static const List<TdsSectionRate> fy202526 = [
    TdsSectionRate(
      section: '192',
      subSection: '',
      description: 'Salary',
      rateIndividualHuf: 0,
      rateOthers: 0,
      rateNoPan: 30,
      thresholdSingle: 250000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: 'Slab rates apply; 0 is placeholder',
    ),
    TdsSectionRate(
      section: '193',
      subSection: '',
      description: 'Interest on securities',
      rateIndividualHuf: 10,
      rateOthers: 10,
      rateNoPan: 20,
      thresholdSingle: 10000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194',
      subSection: '',
      description: 'Dividends',
      rateIndividualHuf: 10,
      rateOthers: 10,
      rateNoPan: 20,
      thresholdSingle: 5000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194A',
      subSection: '',
      description: 'Interest (other than securities)',
      rateIndividualHuf: 10,
      rateOthers: 10,
      rateNoPan: 20,
      thresholdSingle: 40000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194B',
      subSection: '',
      description: 'Lottery/crossword winnings',
      rateIndividualHuf: 30,
      rateOthers: 30,
      rateNoPan: 30,
      thresholdSingle: 10000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194BB',
      subSection: '',
      description: 'Horse race winnings',
      rateIndividualHuf: 30,
      rateOthers: 30,
      rateNoPan: 30,
      thresholdSingle: 10000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194C',
      subSection: '',
      description: 'Contractor payments',
      rateIndividualHuf: 1,
      rateOthers: 2,
      rateNoPan: 20,
      thresholdSingle: 30000,
      thresholdAggregate: 100000,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194D',
      subSection: '',
      description: 'Insurance commission',
      rateIndividualHuf: 5,
      rateOthers: 5,
      rateNoPan: 20,
      thresholdSingle: 15000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194DA',
      subSection: '',
      description: 'Life insurance maturity',
      rateIndividualHuf: 5,
      rateOthers: 5,
      rateNoPan: 20,
      thresholdSingle: 100000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194E',
      subSection: '',
      description: 'NR sportsperson/entertainer',
      rateIndividualHuf: 20,
      rateOthers: 20,
      rateNoPan: 20,
      thresholdSingle: 0,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194EE',
      subSection: '',
      description: 'NSS deposits',
      rateIndividualHuf: 10,
      rateOthers: 10,
      rateNoPan: 20,
      thresholdSingle: 2500,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194G',
      subSection: '',
      description: 'Lottery commission',
      rateIndividualHuf: 5,
      rateOthers: 5,
      rateNoPan: 20,
      thresholdSingle: 15000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194H',
      subSection: '',
      description: 'Commission/brokerage',
      rateIndividualHuf: 2,
      rateOthers: 2,
      rateNoPan: 20,
      thresholdSingle: 15000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194I(a)',
      subSection: '',
      description: 'Rent - P&M/Equipment',
      rateIndividualHuf: 2,
      rateOthers: 2,
      rateNoPan: 20,
      thresholdSingle: 0,
      thresholdAggregate: 600000,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194I(b)',
      subSection: '',
      description: 'Rent - Land/Building',
      rateIndividualHuf: 10,
      rateOthers: 10,
      rateNoPan: 20,
      thresholdSingle: 0,
      thresholdAggregate: 600000,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194IA',
      subSection: '',
      description: 'Sale of immovable property',
      rateIndividualHuf: 1,
      rateOthers: 1,
      rateNoPan: 20,
      thresholdSingle: 5000000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194IB',
      subSection: '',
      description: 'Rent by individual/HUF',
      rateIndividualHuf: 2,
      rateOthers: 2,
      rateNoPan: 20,
      thresholdSingle: 50000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: 'Per month threshold',
    ),
    TdsSectionRate(
      section: '194J(a)',
      subSection: '',
      description: 'Technical services/call center',
      rateIndividualHuf: 2,
      rateOthers: 2,
      rateNoPan: 20,
      thresholdSingle: 30000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194J(b)',
      subSection: '',
      description: 'Professional/royalty fees',
      rateIndividualHuf: 10,
      rateOthers: 10,
      rateNoPan: 20,
      thresholdSingle: 30000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194K',
      subSection: '',
      description: 'Mutual fund income',
      rateIndividualHuf: 10,
      rateOthers: 10,
      rateNoPan: 20,
      thresholdSingle: 5000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194LA',
      subSection: '',
      description: 'Compulsory acquisition',
      rateIndividualHuf: 10,
      rateOthers: 10,
      rateNoPan: 20,
      thresholdSingle: 250000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194LBC',
      subSection: '',
      description: 'Securitization trust',
      rateIndividualHuf: 10,
      rateOthers: 10,
      rateNoPan: 20,
      thresholdSingle: 0,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194M',
      subSection: '',
      description: 'Commission by individual/HUF',
      rateIndividualHuf: 5,
      rateOthers: 5,
      rateNoPan: 20,
      thresholdSingle: 5000000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194N',
      subSection: '',
      description: 'Cash withdrawal',
      rateIndividualHuf: 2,
      rateOthers: 2,
      rateNoPan: 20,
      thresholdSingle: 10000000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194O',
      subSection: '',
      description: 'E-commerce payments',
      rateIndividualHuf: 1,
      rateOthers: 1,
      rateNoPan: 20,
      thresholdSingle: 500000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194Q',
      subSection: '',
      description: 'Purchase of goods',
      rateIndividualHuf: 0.1,
      rateOthers: 0.1,
      rateNoPan: 20,
      thresholdSingle: 0,
      thresholdAggregate: 5000000,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194R',
      subSection: '',
      description: 'Benefits/perquisites',
      rateIndividualHuf: 10,
      rateOthers: 10,
      rateNoPan: 20,
      thresholdSingle: 20000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '194S',
      subSection: '',
      description: 'Virtual digital assets',
      rateIndividualHuf: 1,
      rateOthers: 1,
      rateNoPan: 20,
      thresholdSingle: 50000,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '195',
      subSection: '',
      description: 'Payment to non-residents',
      rateIndividualHuf: 20,
      rateOthers: 20,
      rateNoPan: 20,
      thresholdSingle: 0,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: 'Plus surcharge and cess',
    ),
    TdsSectionRate(
      section: '206C(1)',
      subSection: '',
      description: 'TCS on scrap/minerals',
      rateIndividualHuf: 1,
      rateOthers: 1,
      rateNoPan: 5,
      thresholdSingle: 0,
      thresholdAggregate: 0,
      financialYear: '2025-26',
      notes: '',
    ),
    TdsSectionRate(
      section: '206C(1H)',
      subSection: '',
      description: 'TCS on sale of goods',
      rateIndividualHuf: 0.1,
      rateOthers: 0.1,
      rateNoPan: 1,
      thresholdSingle: 0,
      thresholdAggregate: 5000000,
      financialYear: '2025-26',
      notes: '',
    ),
  ];
}
