/// Summary of TDS deducted and credited for a single deductor (employer,
/// bank, or any other entity that deducts TDS).
///
/// All monetary amounts are in **paise** (1 INR = 100 paise).
class DeductorTdsSummary {
  const DeductorTdsSummary({
    required this.deductorName,
    required this.deductorTan,
    required this.totalGrossAmount,
    required this.totalTdsDeducted,
    required this.totalTdsCredited,
  });

  /// Name of the deductor (e.g. 'Infosys Ltd', 'HDFC Bank').
  final String deductorName;

  /// Tax Deduction Account Number (TAN) of the deductor.
  final String deductorTan;

  /// Total gross income on which TDS was deducted, in paise.
  final int totalGrossAmount;

  /// Total TDS deducted from the assessee's payments, in paise.
  final int totalTdsDeducted;

  /// Total TDS actually credited in Form 26AS, in paise.
  ///
  /// This may be less than [totalTdsDeducted] if the deductor filed
  /// under the wrong PAN or failed to deposit TDS to the government.
  final int totalTdsCredited;

  /// Difference between deducted and credited amounts, in paise.
  ///
  /// A positive value indicates a shortfall that requires rectification
  /// by the deductor via a correction statement.
  int get creditShortfall => totalTdsDeducted - totalTdsCredited;

  DeductorTdsSummary copyWith({
    String? deductorName,
    String? deductorTan,
    int? totalGrossAmount,
    int? totalTdsDeducted,
    int? totalTdsCredited,
  }) {
    return DeductorTdsSummary(
      deductorName: deductorName ?? this.deductorName,
      deductorTan: deductorTan ?? this.deductorTan,
      totalGrossAmount: totalGrossAmount ?? this.totalGrossAmount,
      totalTdsDeducted: totalTdsDeducted ?? this.totalTdsDeducted,
      totalTdsCredited: totalTdsCredited ?? this.totalTdsCredited,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is DeductorTdsSummary &&
        other.deductorName == deductorName &&
        other.deductorTan == deductorTan &&
        other.totalGrossAmount == totalGrossAmount &&
        other.totalTdsDeducted == totalTdsDeducted &&
        other.totalTdsCredited == totalTdsCredited;
  }

  @override
  int get hashCode => Object.hash(
    deductorName,
    deductorTan,
    totalGrossAmount,
    totalTdsDeducted,
    totalTdsCredited,
  );
}

/// Details of a TDS credit shortfall from a specific deductor.
///
/// Generated by [PanTdsConsolidationService.detectShortCredits] when the TDS
/// deposited by a deductor does not appear in Form 26AS (wrong PAN or
/// non-deposit by deductor).
class ShortCreditItem {
  const ShortCreditItem({
    required this.deductorName,
    required this.deductorTan,
    required this.shortfallAmount,
  });

  /// Name of the deductor with the shortfall.
  final String deductorName;

  /// TAN of the deductor with the shortfall.
  final String deductorTan;

  /// Amount of TDS that was deducted but not credited, in paise.
  final int shortfallAmount;

  ShortCreditItem copyWith({
    String? deductorName,
    String? deductorTan,
    int? shortfallAmount,
  }) {
    return ShortCreditItem(
      deductorName: deductorName ?? this.deductorName,
      deductorTan: deductorTan ?? this.deductorTan,
      shortfallAmount: shortfallAmount ?? this.shortfallAmount,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    return other is ShortCreditItem &&
        other.deductorName == deductorName &&
        other.deductorTan == deductorTan &&
        other.shortfallAmount == shortfallAmount;
  }

  @override
  int get hashCode => Object.hash(deductorName, deductorTan, shortfallAmount);
}

/// Immutable consolidated TDS summary for a single PAN across all deductors
/// for a given assessment year.
///
/// All monetary amounts are in **paise** (1 INR = 100 paise).
///
/// ### Shortfall Explanation
/// `shortfall` = [totalTdsDeducted] − [totalTdsCredited].
/// A non-zero shortfall indicates that some deductors have not deposited
/// the TDS they deducted, or have used an incorrect PAN. The assessee
/// must follow up with those deductors to file correction statements.
class PanTdsConsolidation {
  const PanTdsConsolidation({
    required this.pan,
    required this.assessmentYear,
    required this.deductorWiseSummary,
    required this.totalIncome,
    required this.totalTdsDeducted,
    required this.totalTdsCredited,
    required this.shortfall,
  });

  /// PAN of the assessee.
  final String pan;

  /// Assessment year this consolidation covers (e.g. '2025-26').
  final String assessmentYear;

  /// Per-deductor TDS breakdown.
  final List<DeductorTdsSummary> deductorWiseSummary;

  /// Total gross income across all deductors, in paise.
  final int totalIncome;

  /// Total TDS deducted across all deductors, in paise.
  final int totalTdsDeducted;

  /// Total TDS credited in Form 26AS, in paise.
  final int totalTdsCredited;

  /// TDS deducted but not credited — requires rectification, in paise.
  final int shortfall;

  PanTdsConsolidation copyWith({
    String? pan,
    String? assessmentYear,
    List<DeductorTdsSummary>? deductorWiseSummary,
    int? totalIncome,
    int? totalTdsDeducted,
    int? totalTdsCredited,
    int? shortfall,
  }) {
    return PanTdsConsolidation(
      pan: pan ?? this.pan,
      assessmentYear: assessmentYear ?? this.assessmentYear,
      deductorWiseSummary: deductorWiseSummary ?? this.deductorWiseSummary,
      totalIncome: totalIncome ?? this.totalIncome,
      totalTdsDeducted: totalTdsDeducted ?? this.totalTdsDeducted,
      totalTdsCredited: totalTdsCredited ?? this.totalTdsCredited,
      shortfall: shortfall ?? this.shortfall,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! PanTdsConsolidation) return false;
    if (other.pan != pan) return false;
    if (other.assessmentYear != assessmentYear) return false;
    if (other.totalIncome != totalIncome) return false;
    if (other.totalTdsDeducted != totalTdsDeducted) return false;
    if (other.totalTdsCredited != totalTdsCredited) return false;
    if (other.shortfall != shortfall) return false;
    if (other.deductorWiseSummary.length != deductorWiseSummary.length) {
      return false;
    }
    for (var i = 0; i < deductorWiseSummary.length; i++) {
      if (other.deductorWiseSummary[i] != deductorWiseSummary[i]) return false;
    }
    return true;
  }

  @override
  int get hashCode => Object.hash(
    pan,
    assessmentYear,
    Object.hashAll(deductorWiseSummary),
    totalIncome,
    totalTdsDeducted,
    totalTdsCredited,
    shortfall,
  );
}
