import 'package:ca_app/features/practice/presentation/kanban/kanban_providers.dart';

/// Mock kanban card data for development. 15 cards spread across 5 columns.
///
/// Replace with real data source (Drift DB / Supabase) when available.

final _now = DateTime.now();

final mockKanbanCards = <KanbanCardData>[
  // Backlog (3 cards)
  KanbanCardData(
    id: 'kb-001',
    title: 'ROC Annual Filing — ABC Infra',
    description: 'Prepare and file MGT-7 and AOC-4 for FY 2025-26',
    assignee: 'Neha Kapoor',
    priority: KanbanPriority.medium,
    dueDate: _now.add(const Duration(days: 45)),
    clientName: 'ABC Infra Pvt Ltd',
    columnId: 'backlog',
    tags: ['ROC', 'Annual'],
    subtasks: [
      const KanbanSubtask(
        title: 'Collect board resolutions',
        isCompleted: false,
      ),
      const KanbanSubtask(title: 'Prepare MGT-7', isCompleted: false),
      const KanbanSubtask(title: 'File AOC-4', isCompleted: false),
    ],
    hoursLogged: 0,
  ),
  KanbanCardData(
    id: 'kb-002',
    title: 'Transfer Pricing Study',
    description: 'Prepare TP documentation for international transactions',
    assignee: 'Neha Kapoor',
    priority: KanbanPriority.low,
    dueDate: _now.add(const Duration(days: 90)),
    clientName: 'Bharat Electronics Ltd',
    columnId: 'backlog',
    tags: ['TP', 'International'],
    subtasks: [
      const KanbanSubtask(title: 'Functional analysis', isCompleted: false),
      const KanbanSubtask(title: 'Benchmarking study', isCompleted: false),
    ],
    hoursLogged: 0,
  ),
  KanbanCardData(
    id: 'kb-003',
    title: 'PF/ESI Registration',
    description: 'New PF and ESI registration for recently incorporated entity',
    assignee: 'Priya Nair',
    priority: KanbanPriority.low,
    dueDate: _now.add(const Duration(days: 30)),
    clientName: 'TechVista Solutions LLP',
    columnId: 'backlog',
    tags: ['PF', 'ESI', 'Registration'],
    subtasks: [
      const KanbanSubtask(title: 'PF application', isCompleted: false),
      const KanbanSubtask(title: 'ESI application', isCompleted: false),
    ],
    hoursLogged: 0,
  ),

  // To Do (3 cards)
  KanbanCardData(
    id: 'kb-004',
    title: 'GST Annual Return — GSTR-9',
    description: 'Prepare and file GSTR-9 for FY 2025-26',
    assignee: 'Ramesh Iyer',
    priority: KanbanPriority.high,
    dueDate: _now.add(const Duration(days: 20)),
    clientName: 'Mehta & Sons',
    columnId: 'todo',
    tags: ['GST', 'Annual'],
    subtasks: [
      const KanbanSubtask(
        title: 'Reconcile GSTR-1 vs books',
        isCompleted: false,
      ),
      const KanbanSubtask(title: 'Reconcile ITC', isCompleted: false),
      const KanbanSubtask(title: 'Prepare GSTR-9', isCompleted: false),
    ],
    hoursLogged: 0,
  ),
  KanbanCardData(
    id: 'kb-005',
    title: 'TDS Return 24Q — Q4',
    description: 'Quarterly TDS return for salary deductions',
    assignee: 'Priya Nair',
    priority: KanbanPriority.high,
    dueDate: _now.add(const Duration(days: 15)),
    clientName: 'ABC Infra Pvt Ltd',
    columnId: 'todo',
    tags: ['TDS', 'Quarterly'],
    subtasks: [
      const KanbanSubtask(title: 'Collect challans', isCompleted: true),
      const KanbanSubtask(title: 'Prepare in RPU', isCompleted: false),
      const KanbanSubtask(title: 'FVU validation', isCompleted: false),
    ],
    hoursLogged: 1.5,
  ),
  KanbanCardData(
    id: 'kb-006',
    title: 'Advance Tax — Q4 Estimate',
    description: 'Compute and deposit Q4 advance tax before 15 March',
    assignee: 'Amit Verma',
    priority: KanbanPriority.critical,
    dueDate: _now.add(const Duration(days: 3)),
    clientName: 'Deepak Patel',
    columnId: 'todo',
    tags: ['Advance Tax', 'Urgent'],
    subtasks: [
      const KanbanSubtask(title: 'Estimate total income', isCompleted: true),
      const KanbanSubtask(title: 'Compute tax liability', isCompleted: false),
      const KanbanSubtask(title: 'Generate challan', isCompleted: false),
    ],
    hoursLogged: 2,
  ),

  // In Progress (4 cards)
  KanbanCardData(
    id: 'kb-007',
    title: 'Statutory Audit — Fieldwork',
    description: 'Vouching, verification, and confirmation procedures',
    assignee: 'Neha Kapoor',
    priority: KanbanPriority.critical,
    dueDate: _now.add(const Duration(days: 10)),
    clientName: 'ABC Infra Pvt Ltd',
    columnId: 'in_progress',
    tags: ['Audit', 'Fieldwork'],
    subtasks: [
      const KanbanSubtask(title: 'Revenue testing', isCompleted: true),
      const KanbanSubtask(title: 'Expense vouching', isCompleted: true),
      const KanbanSubtask(title: 'Bank confirmations', isCompleted: false),
      const KanbanSubtask(title: 'Debtors circularisation', isCompleted: false),
    ],
    hoursLogged: 28,
  ),
  KanbanCardData(
    id: 'kb-008',
    title: 'ITR-1 Filing — Rajesh Kumar',
    description: 'Prepare and file ITR-1 for salaried individual',
    assignee: 'Amit Verma',
    priority: KanbanPriority.medium,
    dueDate: _now.add(const Duration(days: 5)),
    clientName: 'Rajesh Kumar Sharma',
    columnId: 'in_progress',
    tags: ['ITR', 'Individual'],
    subtasks: [
      const KanbanSubtask(title: 'Collect Form 16', isCompleted: true),
      const KanbanSubtask(title: 'Verify 26AS/AIS', isCompleted: true),
      const KanbanSubtask(title: 'Compute income', isCompleted: false),
      const KanbanSubtask(title: 'File on portal', isCompleted: false),
    ],
    hoursLogged: 3.5,
  ),
  KanbanCardData(
    id: 'kb-009',
    title: 'GSTR-3B — March 2026',
    description: 'Monthly GST return filing for March',
    assignee: 'Ramesh Iyer',
    priority: KanbanPriority.high,
    dueDate: _now.subtract(const Duration(days: 2)),
    clientName: 'Priya Mehta',
    columnId: 'in_progress',
    tags: ['GST', 'Monthly', 'Overdue'],
    subtasks: [
      const KanbanSubtask(title: 'Download GSTR-2B', isCompleted: true),
      const KanbanSubtask(title: 'Reconcile ITC', isCompleted: true),
      const KanbanSubtask(title: 'Compute liability', isCompleted: true),
      const KanbanSubtask(title: 'File on portal', isCompleted: false),
    ],
    hoursLogged: 5,
  ),
  KanbanCardData(
    id: 'kb-010',
    title: 'Monthly Bookkeeping — Feb',
    description: 'Record all transactions and reconcile bank statements',
    assignee: 'Suresh Reddy',
    priority: KanbanPriority.medium,
    dueDate: _now.subtract(const Duration(days: 1)),
    clientName: 'Mehta & Sons',
    columnId: 'in_progress',
    tags: ['Bookkeeping', 'Overdue'],
    subtasks: [
      const KanbanSubtask(title: 'Purchase entries', isCompleted: true),
      const KanbanSubtask(title: 'Sales entries', isCompleted: true),
      const KanbanSubtask(title: 'Bank reconciliation', isCompleted: false),
    ],
    hoursLogged: 6,
  ),

  // Review (2 cards)
  KanbanCardData(
    id: 'kb-011',
    title: 'ITR-4 Filing — GreenLeaf',
    description: 'Presumptive income return under section 44AD',
    assignee: 'Ramesh Iyer',
    priority: KanbanPriority.medium,
    dueDate: _now.add(const Duration(days: 8)),
    clientName: 'GreenLeaf Organics LLP',
    columnId: 'review',
    tags: ['ITR', 'Presumptive'],
    subtasks: [
      const KanbanSubtask(
        title: 'Compute presumptive income',
        isCompleted: true,
      ),
      const KanbanSubtask(title: 'Prepare return', isCompleted: true),
      const KanbanSubtask(title: 'Partner review', isCompleted: false),
    ],
    hoursLogged: 4,
  ),
  KanbanCardData(
    id: 'kb-012',
    title: 'GST Registration Amendment',
    description: 'Amend principal place of business on GST portal',
    assignee: 'Priya Nair',
    priority: KanbanPriority.low,
    dueDate: _now.add(const Duration(days: 7)),
    clientName: 'GreenLeaf Organics LLP',
    columnId: 'review',
    tags: ['GST', 'Amendment'],
    subtasks: [
      const KanbanSubtask(
        title: 'Prepare amendment application',
        isCompleted: true,
      ),
      const KanbanSubtask(title: 'Upload documents', isCompleted: true),
      const KanbanSubtask(title: 'Submit for review', isCompleted: true),
    ],
    hoursLogged: 2,
  ),

  // Done (3 cards)
  KanbanCardData(
    id: 'kb-013',
    title: 'TDS Return 26Q — Q3',
    description: 'Non-salary TDS return filed successfully',
    assignee: 'Priya Nair',
    priority: KanbanPriority.medium,
    dueDate: _now.subtract(const Duration(days: 5)),
    clientName: 'TechVista Solutions LLP',
    columnId: 'done',
    tags: ['TDS', 'Filed'],
    subtasks: [
      const KanbanSubtask(title: 'Collect challans', isCompleted: true),
      const KanbanSubtask(title: 'Prepare in RPU', isCompleted: true),
      const KanbanSubtask(title: 'File on TRACES', isCompleted: true),
    ],
    hoursLogged: 5,
  ),
  KanbanCardData(
    id: 'kb-014',
    title: 'GSTR-1 — Feb 2026',
    description: 'Outward supply return filed for February',
    assignee: 'Ramesh Iyer',
    priority: KanbanPriority.medium,
    dueDate: _now.subtract(const Duration(days: 6)),
    clientName: 'Mehta & Sons',
    columnId: 'done',
    tags: ['GST', 'Filed'],
    subtasks: [
      const KanbanSubtask(title: 'Export invoices', isCompleted: true),
      const KanbanSubtask(title: 'File GSTR-1', isCompleted: true),
    ],
    hoursLogged: 3,
  ),
  KanbanCardData(
    id: 'kb-015',
    title: 'Company Incorporation — TechVista',
    description: 'SPICe+ incorporation completed with PAN/TAN',
    assignee: 'Amit Verma',
    priority: KanbanPriority.high,
    dueDate: _now.subtract(const Duration(days: 10)),
    clientName: 'TechVista Solutions LLP',
    columnId: 'done',
    tags: ['ROC', 'Incorporation'],
    subtasks: [
      const KanbanSubtask(title: 'Name reservation', isCompleted: true),
      const KanbanSubtask(title: 'Draft MOA/AOA', isCompleted: true),
      const KanbanSubtask(title: 'File SPICe+', isCompleted: true),
      const KanbanSubtask(title: 'PAN/TAN received', isCompleted: true),
    ],
    hoursLogged: 18,
  ),
];
