import 'package:flutter_test/flutter_test.dart';
import 'package:ca_app/features/gstn_api/data/mock_gstn_repository.dart';
import 'package:ca_app/features/gstn_api/data/repositories/gstn_api_repository_impl.dart';
import 'package:ca_app/features/gstn_api/domain/models/gstn_verification_result.dart';
import 'package:ca_app/features/gstn_api/domain/models/gstn_filing_status.dart';
import 'package:ca_app/features/gstn_api/domain/models/gstr2b_fetch_result.dart';

void main() {
  group('MockGstnRepository', () {
    late MockGstnRepository repo;

    setUp(() {
      repo = MockGstnRepository();
    });

    group('verifyGstin', () {
      test('returns active result for 15-char GSTIN', () async {
        final result = await repo.verifyGstin('29ABCDE1234F1Z5');
        expect(result.status, GstnRegistrationStatus.active);
        expect(result.gstin, '29ABCDE1234F1Z5');
      });

      test('returns cancelled for invalid length', () async {
        final result = await repo.verifyGstin('INVALID');
        expect(result.status, GstnRegistrationStatus.cancelled);
      });
    });

    group('saveReturn', () {
      test('returns saved status', () async {
        final result = await repo.saveReturn(
          '29ABCDE1234F1Z5',
          'GSTR1',
          '032024',
          '{}',
        );
        expect(result.status, GstnReturnStatus.saved);
        expect(result.returnType, GstnReturnType.gstr1);
      });
    });

    group('submitReturn', () {
      test('returns submitted status', () async {
        final result = await repo.submitReturn(
          '29ABCDE1234F1Z5',
          'GSTR3B',
          '032024',
        );
        expect(result.status, GstnReturnStatus.submitted);
        expect(result.returnType, GstnReturnType.gstr3b);
      });
    });

    group('fileReturn', () {
      test('returns filed status with filedAt', () async {
        final result = await repo.fileReturn(
          '29ABCDE1234F1Z5',
          'GSTR1',
          '032024',
          '123456',
        );
        expect(result.status, GstnReturnStatus.filed);
        expect(result.filedAt, isNotNull);
      });
    });

    group('getFilingStatus', () {
      test('returns filing status', () async {
        final result = await repo.getFilingStatus(
          '29ABCDE1234F1Z5',
          'GSTR1',
          '032024',
        );
        expect(result.gstin, '29ABCDE1234F1Z5');
        expect(result.period, '032024');
      });
    });

    group('fetchGstr2b', () {
      test('returns result with entry count', () async {
        final result = await repo.fetchGstr2b('29ABCDE1234F1Z5', '032024');
        expect(result.status, Gstr2bStatus.generated);
        expect(result.entryCount, greaterThan(0));
      });
    });

    group('getToken', () {
      test('returns token with Bearer type', () async {
        final result = await repo.getToken(
          '29ABCDE1234F1Z5',
          'user@test.com',
          '123456',
        );
        expect(result.tokenType, 'Bearer');
        expect(result.accessToken, isNotEmpty);
      });
    });
  });

  group('GstnApiRepositoryImpl', () {
    late GstnApiRepositoryImpl repo;

    setUp(() {
      repo = const GstnApiRepositoryImpl();
    });

    group('verifyGstin', () {
      test('returns active for 15-char GSTIN', () async {
        final result = await repo.verifyGstin('29ABCDE1234F1Z5');
        expect(result.status, GstnRegistrationStatus.active);
      });

      test('returns cancelled for invalid length', () async {
        final result = await repo.verifyGstin('INVALID');
        expect(result.status, GstnRegistrationStatus.cancelled);
      });
    });

    group('getFilingStatus', () {
      test('returns not-filed by default', () async {
        final result = await repo.getFilingStatus(
          '29ABCDE1234F1Z5',
          'GSTR1',
          '032024',
        );
        expect(result.status, GstnReturnStatus.notFiled);
      });
    });

    group('fetchGstr2b', () {
      test('returns not-generated by default', () async {
        final result = await repo.fetchGstr2b('29ABCDE1234F1Z5', '032024');
        expect(result.status, Gstr2bStatus.notGenerated);
        expect(result.entryCount, 0);
      });
    });
  });
}
