/// The type of notice or legal document being drafted.
enum NoticeType {
  reply143_1,
  reply143_3,
  appeal,
  rectification,
  condonation,
  penalty,
  revision,
}

/// An immutable drafted notice or legal response generated by the knowledge engine.
///
/// Use [copyWith] to derive a modified copy without mutating the original.
class NoticeDraft {
  const NoticeDraft({
    required this.draftId,
    required this.noticeType,
    required this.originalNoticeDate,
    required this.assessmentYear,
    required this.taxpayerName,
    required this.pan,
    required this.groundsOfAppeal,
    required this.draftText,
    required this.templateUsed,
  });

  final String draftId;
  final NoticeType noticeType;
  final DateTime originalNoticeDate;

  /// Assessment year in "YYYY-YY" format, e.g. "2024-25".
  final String assessmentYear;

  final String taxpayerName;
  final String pan;

  /// List of grounds for appeal or contention.
  final List<String> groundsOfAppeal;

  /// The full text of the drafted notice/reply.
  final String draftText;

  /// Identifier of the template used to generate this draft.
  final String templateUsed;

  NoticeDraft copyWith({
    String? draftId,
    NoticeType? noticeType,
    DateTime? originalNoticeDate,
    String? assessmentYear,
    String? taxpayerName,
    String? pan,
    List<String>? groundsOfAppeal,
    String? draftText,
    String? templateUsed,
  }) {
    return NoticeDraft(
      draftId: draftId ?? this.draftId,
      noticeType: noticeType ?? this.noticeType,
      originalNoticeDate: originalNoticeDate ?? this.originalNoticeDate,
      assessmentYear: assessmentYear ?? this.assessmentYear,
      taxpayerName: taxpayerName ?? this.taxpayerName,
      pan: pan ?? this.pan,
      groundsOfAppeal: groundsOfAppeal ?? this.groundsOfAppeal,
      draftText: draftText ?? this.draftText,
      templateUsed: templateUsed ?? this.templateUsed,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other is! NoticeDraft) return false;
    if (other.draftId != draftId ||
        other.noticeType != noticeType ||
        other.originalNoticeDate != originalNoticeDate ||
        other.assessmentYear != assessmentYear ||
        other.taxpayerName != taxpayerName ||
        other.pan != pan ||
        other.draftText != draftText ||
        other.templateUsed != templateUsed) {
      return false;
    }
    if (other.groundsOfAppeal.length != groundsOfAppeal.length) return false;
    for (int i = 0; i < groundsOfAppeal.length; i++) {
      if (other.groundsOfAppeal[i] != groundsOfAppeal[i]) return false;
    }
    return true;
  }

  @override
  int get hashCode => Object.hash(
    draftId,
    noticeType,
    originalNoticeDate,
    assessmentYear,
    taxpayerName,
    pan,
    Object.hashAll(groundsOfAppeal),
    draftText,
    templateUsed,
  );
}
